include_recipe 'typo3-flow::system'
include_recipe 'typo3-flow::mysql'
include_recipe 'typo3-flow::nginx'
include_recipe 'typo3-flow::php'
include_recipe 'typo3-flow::user'
include_recipe 'typo3-flow::nfs'
include_recipe 'typo3-flow::flow'