name             'typo3-flow'
maintainer       'Michael Gerdemann'
maintainer_email 'michael.gerdemann@w-s-n.de'
license          'GPL 2'
description      'TYPO3 Flow'
long_description ''
version          '0.0.1'

depends 'yum'
depends 'mysql'
depends 'database'
depends 'nginx'
depends 'php', '~> 1.2.0'
depends 'php-fpm'
depends 'composer'
depends 'nfs'